config/routes.rb
Rails.application.routes.draw do


devise_for :designers, controllers: {
  sessions:      'designers/sessions',
  passwords:     'designers/passwords',
  registrations: 'designers/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

root 'styles#top'
get 'styles/index' => 'styles#index'
get 'styles/news' => 'styles#news'
get 'styles/:id' => 'styles#show'

  resources :users, only: :show
  resources :styles do
    resources :likes, only: [:create, :destroy]
  end
# resources :scrap, only: [:index, :show] do
  # resources :likes, only: [:create, :destroy]
# end
get 'designer/new'=> 'designers#new'
# get 'designers/:id'=> 'designers#index'
get 'users/:id' => 'users#show'


get 'designers/:id' => 'designers#show'



end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :style, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(user_id: current_user.id, style_id: params[:style_id])
    @likes = Like.where(style_id: params[:style_id])
    @style = Style.find(params[:style_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, style_id: params[:style_id])
    like.destroy
    @likes = Like.where(style_id: params[:style_id])
    @style = Style.find(params[:style_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if style.like_user(current_user.id) %>
    <%= button_to style_like_path(style,current_user), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("likes-heart1.png") %>
    <span><%= style.likes_count %></span>
    <% end %>
  <% else %>
    <%= button_to style_likes_path(style), id: "like-button", remote: true do %>
      <%= image_tag("likes-heart0.png") %>
      <span><%= style.likes_count %></span>
      <% end %>
  <% end %>
    <% else %>
      <%= image_tag("likes-heart0.png") %>
      <span><%= style.likes_count %></span>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { style: @style, likes: @likes, like: @like}) %>")

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { style: @style, likes: @likes }) %>");

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>