config/routes.rb
Rails.application.routes.draw do


devise_for :designers, controllers: {
  sessions:      'designers/sessions',
  passwords:     'designers/passwords',
  registrations: 'designers/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

root 'styles#top'
get 'styles/index' => 'styles#index'
get 'styles/news' => 'styles#news'
get 'styles/:id' => 'styles#show'

  resources :users, only: :show
  resources :styles do
    resources :likes, only: [:create, :destroy]
  end
# resources :scrap, only: [:index, :show] do
  # resources :likes, only: [:create, :destroy]
# end
get 'designer/new'=> 'designers#new'
# get 'designers/:id'=> 'designers#index'
get 'users/:id' => 'users#show'


get 'designers/:id' => 'designers#show'



end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :designer
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  def top
  end

  def news
  end

  def index
    @styles = Style.includes(:designer).order("id ASC").page(params[:page]).per(20)
    @style = Style.all
    # @style_id = Like.find(:id)
    # @styles = Style.order("id ASC").page(params[:page]).per(20)
    # @like = Like.find_by(style_id: 4)
  end


  def new
    @style = Style.new
  end

  def show
    @style = Style.find(params[:id])
    # @styles = Style.order("id ASC").page(params[:page]).per(20)
    # @style = Style.find(params[:id])
    # @likes = Like.where(style_id: params[:id])
  end

  def create
    Style.create(designer: style_params[:designer], shop_name: style_params[:shop_name], image: style_params[:image], designer_id: current_designer.id)
  end

  def destroy
    style = Style.find(params[:id])
    if style.designer_id == current_designer.id
      style.destroy
    end
  end

  private
  def style_params
    params.permit(:designer, :shop_name, :image)
  end

end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<% @styles.each do |style| %>
  <div class="col-xs-6 col-md-3">
  <!--   <a href="/styles/<%= style.designer %>"></a> -->
    <img src="<%= style.image %>" class="img-thumbnail"></br>
    <!-- <%= style.designer %> -->
    <div class="likes-heart">
    <%= render partial: "likes/like", locals: { style: style } %>
    </div>
   </a>
 </div>
<%end%>

<%= paginate @styles %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/news.html.erb
<div class="media">
  <div class="media-left media-middle">
    <a href="#">
      <img class="media-object" src="http://dqaeric34olch.cloudfront.net/lists/216780/12751069_966089923446293_46847946_n.jpg/thumb?1456642936" alt="">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><a>髪が伸びたらこうしたいっ♪憧れのロングヘア18連発</a></h4>
    <p>2016春の最旬トレンドヘアスタイルをひとまとめ。18のおしゃれヘアスタイルをインスタグラムから紹介します！</br>（近年インスタグラムを利用した個人でのブランディングが主流になり特にハッシュタグ[＃サロンモデル]でのアップロード件数については毎日かなりの数が掲載され電子ヘアカタログのような状況になっています。ユーザーはそこからその美容師のところへ行ったり、直接来店に繋がらないにしてもカウンセリングの際、担当とイメージを共有するツールの一つとして使われている傾向があります。</p>
  </div>
</div>
<div class="media">
  <div class="media-left media-middle">
    <a href="#">
      <img class="media-object" src="http://dqaeric34olch.cloudfront.net/lists/218179/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88_2016-03-03_18.30.07.png/thumb?1456997421" alt="">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><a>編み込みは苦手です。簡単ハープアップヘアアレンジで不器用さんでも今年顔に♡</a></h4>
    <p>編み込みやねじるといった細かいアレンジは苦手。そんな不器用さんに送るハーフアップアレンジ。普段〜パーティーシーンまで使える気合いの入りすぎないラフで可愛いスタイルをご紹介します！</br>(従来では写真による掲載でわかりにくかったヘアアレンジなどもHowTo動画コンテンツなどを充実させる事でアクセス数ならびに閲覧数の増加へつなげます。)</p>
  </div>
</div>
<div class="media">
  <div class="media-left media-middle">
    <a href="#">
      <img class="media-object" src="http://office-mighty.com/image/profile11.png" alt="">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><a>連載企画第8弾!菊本氏による40代からのアンチエイジング</a></h4>
    <p>年を重ねる事をネガティブな事としない！年を重ねるからこそ出せる良い物がある！無理な若作りをせず綺麗になれるヘアスタイル</br>娘と母親の距離が近い今、ふとしたきっかけで30〜40代の美容に対する意識は変わってきます。特に親子で出かける際に娘が可愛くしていれば母親も一緒に綺麗にいたいと思うもの。子供がある程度離れたからこそ自分に時間をかけられる世代でもあり、この世代は特に美容市場としてもボリュームゾーンです。綺麗になるきっかけは娘からの影響！？</p>
  </div>
</div>
<div class="media">
  <div class="media-left media-middle">
    <a href="#">
      <img class="media-object" src="https://hagelabo.jp/uploads/picture/image/284/thumbnail_imasia_14750835_L.jpg" alt="">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><a>薄毛の男性にも似合う髪型はある！隠すよりも出す！？イケてる大人のヘアスタイル</a></h4>
    <p>少ない毛量やペタッとしやすい髪質でも髪型とスタイリングでイケてるオヤジスタイルへ！悩める男を救う厳選メンズヘアスタイル！</br>もちろん男性向けのNewsやコラムも行っていきます。直接的に閲覧者へアプローチするのはもちろんの事、他人に紹介したくなるような切り込んだ記事なども掲載していきたいと思います。</p>
  </div>
</div>

app/views/styles/show.html.erb
<<<<<<< HEAD


<% @styles.each do |style| %>
    <div class="col-xs-6 col-md-3">
    <a href="/styles/<%= style.designer %>">
      <img src="<%= style.image %>" class="img-thumbnail">
      <h3 name="<%= style.designer %>">
     </a>
   </div>
  <%end%>

  <%= paginate @styles %>
=======
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>
>>>>>>> 19344abf19d39144ea0cbb40a2c0134aeefac1e0

app/views/styles/top.html.erb
<!-- top image&text -->
<figure class="relative">
  <img src="https://d1uzk9o9cg136f.cloudfront.net/f/16781160/rc/2015/07/16/9164b300d01b2fcf244fa1fd62ab5ad255ba3fe6.png" alt="SCRSP" class="img-rounded">

  <figcaption class="absolute"><h1>StyleBook / Prototype</h1>
    <p>/stylebook/prototype/localhost:300/</p></figcaption>
</<figure>
<!-- top image&text -->